services:
  satisfactory-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_USER=${DOCKER_USER}
        - DOCKER_GROUP=${DOCKER_GROUP}
    image: 'satisfactory-arm64'
    container_name: 'satisfactory-server'
    security_opt:
      - seccomp:unconfined
    user: "${DOCKER_USER}:${DOCKER_GROUP}"   # Set the user and group from environment variables (look the .env file)
    ports:
      - '15777:15777/udp'
      - '15000:15000/udp'
      - '7777:7777/udp'
      - '7777:7777/tcp'
    restart: 'unless-stopped'
    environment:
      - EXTRA_PARAMS=-log -unattended -ini:Engine:[HTTPServer.Listeners]:DefaultBindAddress=any
    volumes:
      - './server-files:/home/steam/sfserver'
      - './config:/home/steam/.config/Epic'
