services:
  satisfactory-server:
    image: 'satisfactory-arm64'
    security_opt:
      - seccomp:unconfined
    ports:
      - '15777:15777/udp'
      - '15000:15000/udp'
      - '7777:7777/udp'
      - '7777:7777/tcp'
    restart: 'unless-stopped'
    environment:
      - EXTRA_PARAMS=-log -unattended -ini:Engine:[HTTPServer.Listeners]:DefaultBindAddress=any
    volumes:
      - 'steam-files:/home/steam/Steam'
      - 'server-files:/home/steam/sfserver'
      - 'config:/home/steam/.config'

volumes:
  steam-files:
  server-files:
  config:
