version: '3.9'
services:
  satisfactory-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'satisfactory-arm64'
    container_name: 'satisfactory-server'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    restart: 'unless-stopped'
    environment:
      - EXTRA_PARAMS=-log -unattended -ini:Engine:[HTTPServer.Listeners]:DefaultBindAddress=any
    volumes:
      - './satisfactory:/satisfactory'
      - './config:/home/steam/.config/Epic'
    user: "${DOCKER_USER}:${DOCKER_GROUP}"   # Set the user and group from environment variables
    healthcheck:
      test: telnet 127.0.0.1 7777 || exit 1
      start_period: 180s
      timeout: 10s
      interval: 10s
      retries: 3
